### ISSUE TITLE
MotionPlanning warning in Rviz

### ISSUE THREAD

**Issue by EbrahimAlmajed** [ycheng517/ar4_ros_driver#8]
Hello I'm new to ros2 and rvis and i wanted to test AR4 in gazebo and when i tried to use MotionPlanning i get this warning and a plan error.
![Screenshot from 2024-05-01 21-28-28](https://github.com/ycheng517/ar4_ros_driver/assets/51866365/c3431143-e969-4ff7-a425-ad4be69aa839)

Not sure if this is related but i use `rosdep install --from-paths . --ignore-src -r -y`
I get the following error
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
ar_hardware_interface: Cannot locate rosdep definition for [ros2_aruco]
ar_hand_eye: Cannot locate rosdep definition for [ros2_aruco_interfaces]
```
using ros2 iron on ubuntu 22.04

**Comment by ycheng517** [comment]
Ah sorry, this is because the external repos needed for hand-eye calibration is missing. Try running `vcs import . --input ar_hand_eye/hand_eye_calibration.repos`. Will update the instructions to include this step.

**Comment by EbrahimAlmajed** [comment]
Thank you for replying, unfortunately now I get this error in Rviz 
`[ERROR] [move_group-1]: process has died [pid 54326, exit code -6, cmd '/home/user/ws_moveit/install/moveit_ros_move_group/lib/moveit_ros_move_group/move_group --ros-args --params-file /tmp/launch_params_ezlnto9e --params-file /tmp/launch_params__m708mf8 --params-file /tmp/launch_params_73ugkyn4 --params-file /tmp/launch_params_x9zh94vk --params-file /tmp/launch_params_1sw2fyya --params-file /tmp/launch_params_13bwn6j1 --params-file /tmp/launch_params_3mizdyug --params-file /tmp/launch_params_51v3bk_o --params-file /tmp/launch_params_0xej9lo1'].`

this is the full log when running Rviz
```
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [move_group-1]: process started with pid [54695]
[INFO] [rviz2-2]: process started with pid [54697]
[move_group-1] [WARN] [1714671376.411488260] [move_group]: Falling back to using the the move_group node namespace (deprecated behavior).
[move_group-1] [INFO] [1714671376.433386905] [move_group.moveit.moveit.ros.rdf_loader]: Loaded robot model in 0 seconds
[move_group-1] [INFO] [1714671376.433424576] [move_group.moveit.moveit.core.robot_model]: Loading robot model 'ar'...
[move_group-1] [INFO] [1714671376.433438716] [move_group.moveit.moveit.core.robot_model]: No root/virtual joint specified in SRDF. Assuming fixed joint
[move_group-1] [INFO] [1714671376.479300615] [move_group.moveit.moveit.kinematics.kdl_kinematics_plugin]: Joint weights for group 'ar_manipulator': 1 1 1 1 1 1
[move_group-1] [INFO] [1714671376.618743989] [move_group.moveit.moveit.ros.planning_scene_monitor]: Publishing maintained planning scene on 'monitored_planning_scene'
[move_group-1] [INFO] [1714671376.618838940] [move_group.moveit.moveit.ros.moveit_cpp]: Listening to 'joint_states' for joint states
[move_group-1] [INFO] [1714671376.619307859] [move_group.moveit.moveit.ros.current_state_monitor]: Listening to joint states on topic 'joint_states'
[move_group-1] [INFO] [1714671376.619539883] [move_group.moveit.moveit.ros.planning_scene_monitor]: Listening to '/attached_collision_object' for attached collision objects
[move_group-1] [INFO] [1714671376.619551524] [move_group.moveit.moveit.ros.planning_scene_monitor]: Stopping existing planning scene publisher.
[move_group-1] [INFO] [1714671376.619619405] [move_group.moveit.moveit.ros.planning_scene_monitor]: Stopped publishing maintained planning scene.
[move_group-1] [INFO] [1714671376.619766218] [move_group.moveit.moveit.ros.planning_scene_monitor]: Publishing maintained planning scene on 'monitored_planning_scene'
[move_group-1] [INFO] [1714671376.619804588] [move_group.moveit.moveit.ros.planning_scene_monitor]: Starting planning scene monitor
[move_group-1] [INFO] [1714671376.620182326] [move_group.moveit.moveit.ros.planning_scene_monitor]: Listening to '/planning_scene'
[move_group-1] [INFO] [1714671376.620193166] [move_group.moveit.moveit.ros.planning_scene_monitor]: Starting world geometry update monitor for collision objects, attached objects, octomap updates.
[move_group-1] [INFO] [1714671376.620367729] [move_group.moveit.moveit.ros.planning_scene_monitor]: Listening to 'collision_object'
[move_group-1] [INFO] [1714671376.620550932] [move_group.moveit.moveit.ros.planning_scene_monitor]: Listening to 'planning_scene_world' for planning scene world geometry
[move_group-1] [WARN] [1714671376.621857017] [move_group.moveit.moveit.ros.occupancy_map_monitor]: Resolution not specified for Octomap. Assuming resolution = 0.1 instead
[move_group-1] [ERROR] [1714671376.621870227] [move_group.moveit.moveit.ros.occupancy_map_monitor]: No 3D sensor plugin(s) defined for octomap updates
[move_group-1] terminate called after throwing an instance of 'rclcpp::ParameterTypeException'
[move_group-1]   what():  expected [string_array] got [string]
[move_group-1] Stack trace (most recent call last):
[move_group-1] #17   Object "", at 0xffffffffffffffff, in 
[move_group-1] #16   Object "/home/user/ws_moveit/install/moveit_ros_move_group/lib/moveit_ros_move_group/move_group", at 0x58db53968204, in _start
[move_group-1] #15   Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7dd6ff029e3f, in __libc_start_main
[move_group-1] #14   Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7dd6ff029d8f, in 
[move_group-1] #13   Object "/home/user/ws_moveit/install/moveit_ros_move_group/lib/moveit_ros_move_group/move_group", at 0x58db539671c3, in main
[move_group-1] #12   Object "/home/user/ws_moveit/install/moveit_ros_planning/lib/libmoveit_cpp.so.2.9.0", at 0x7dd6fffdb6a7, in moveit_cpp::MoveItCpp::MoveItCpp(std::shared_ptr<rclcpp::Node> const&, moveit_cpp::MoveItCpp::Options const&)
[move_group-1] #11   Object "/home/user/ws_moveit/install/moveit_ros_planning/lib/libmoveit_cpp.so.2.9.0", at 0x7dd6fffda5cb, in moveit_cpp::MoveItCpp::loadPlanningPipelines(moveit_cpp::MoveItCpp::PlanningPipelineOptions const&)
[move_group-1] #10   Object "/home/user/ws_moveit/install/moveit_ros_planning/lib/libmoveit_planning_pipeline_interfaces.so.2.9.0", at 0x7dd6ffa7efab, in moveit::planning_pipeline_interfaces::createPlanningPipelineMap(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::shared_ptr<moveit::core::RobotModel const> const&, std::shared_ptr<rclcpp::Node> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
[move_group-1] #9    Object "/home/user/ws_moveit/install/moveit_ros_planning/lib/libmoveit_planning_pipeline.so.2.9.0", at 0x7dd6ff6bbfc5, in planning_pipeline::PlanningPipeline::PlanningPipeline(std::shared_ptr<moveit::core::RobotModel const> const&, std::shared_ptr<rclcpp::Node> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
[move_group-1] #8    Object "/home/user/ws_moveit/install/moveit_ros_planning/lib/libmoveit_planning_pipeline.so.2.9.0", at 0x7dd6ff6fd63d, in planning_pipeline_parameters::ParamListener::declare_params()
[move_group-1] #7    Object "/opt/ros/iron/lib/librclcpp.so", at 0x7dd6ff8d9869, in 
[move_group-1] #6    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x7dd6ff4ae4d7, in __cxa_throw
[move_group-1] #5    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x7dd6ff4ae276, in std::terminate()
[move_group-1] #4    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x7dd6ff4ae20b, in 
[move_group-1] #3    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x7dd6ff4a2b9d, in 
[move_group-1] #2    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7dd6ff0287f2, in abort
[move_group-1] #1    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7dd6ff042475, in raise
[move_group-1] #0    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7dd6ff0969fc, in pthread_kill
[move_group-1] Aborted (Signal sent by tkill() 54695 1000)
[ERROR] [move_group-1]: process has died [pid 54695, exit code -6, cmd '/home/user/ws_moveit/install/moveit_ros_move_group/lib/moveit_ros_move_group/move_group --ros-args --params-file /tmp/launch_params_igw3g5un --params-file /tmp/launch_params_gqvww0vw --params-file /tmp/launch_params_7sled9u0 --params-file /tmp/launch_params_l74si9ot --params-file /tmp/launch_params_0v2qdjs_ --params-file /tmp/launch_params_uxnv7i33 --params-file /tmp/launch_params_d2f36upz --params-file /tmp/launch_params_iohlymv2 --params-file /tmp/launch_params__h8u8ycv'].
[rviz2-2] [INFO] [1714671376.776936700] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-2] [INFO] [1714671376.776990621] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-2] [INFO] [1714671376.791442209] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-2] Warning: class_loader.impl: SEVERE WARNING!!! A namespace collision has occurred with plugin factory for class rviz_default_plugins::displays::InteractiveMarkerDisplay. New factory will OVERWRITE existing one. This situation occurs when libraries containing plugins are directly linked against an executable (the one running right now generating this message). Please separate plugins out into their own library or just don't link against the library and use either class_loader::ClassLoader/MultiLibraryClassLoader to open.
[rviz2-2]          at line 321 in /opt/ros/iron/include/class_loader/class_loader/class_loader_core.hpp
[rviz2-2] [WARN] [1714671376.885429341] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[rviz2-2] [ERROR] [1714671379.904367465] [rviz2_moveit.moveit.ros.motion_planning_frame]: Action server: /recognize_objects not available
[rviz2-2] [INFO] [1714671379.926321852] [rviz2_moveit.moveit.ros.motion_planning_frame]: MoveGroup namespace changed: / -> . Reloading params.
[rviz2-2] [INFO] [1714671380.000076019] [rviz2_moveit.moveit.ros.rdf_loader]: Loaded robot model in 0.0225252 seconds
[rviz2-2] [INFO] [1714671380.000140870] [rviz2_moveit.moveit.core.robot_model]: Loading robot model 'ar'...
[rviz2-2] [INFO] [1714671380.000157560] [rviz2_moveit.moveit.core.robot_model]: No root/virtual joint specified in SRDF. Assuming fixed joint
[rviz2-2] [INFO] [1714671380.061348584] [rviz2_moveit.moveit.kinematics.kdl_kinematics_plugin]: Joint weights for group 'ar_manipulator': 1 1 1 1 1 1
[rviz2-2] [INFO] [1714671380.202215224] [rviz2_moveit.moveit.ros.planning_scene_monitor]: Starting planning scene monitor
[rviz2-2] [INFO] [1714671380.203221722] [rviz2_moveit.moveit.ros.planning_scene_monitor]: Listening to '/monitored_planning_scene'
[rviz2-2] [INFO] [1714671380.291533890] [interactive_marker_display_97822652761904]: Connected on namespace: /rviz_moveit_motion_planning_display/robot_interaction_interactive_marker_topic
[rviz2-2] [INFO] [1714671380.303104504] [interactive_marker_display_97822652761904]: Sending request for interactive markers
[rviz2-2] [INFO] [1714671380.337821537] [interactive_marker_display_97822652761904]: Service response received for initialization
[rviz2-2] [INFO] [1714671385.296156137] [rviz2_moveit.moveit.ros.planning_scene_monitor]: Failed to call service get_planning_scene, have you launched move_group or called psm.providePlanningSceneService()?
[rviz2-2] [INFO] [1714671385.296257859] [rviz2_moveit.moveit.ros.motion_planning_frame]: group ar_manipulator
[rviz2-2] [INFO] [1714671385.296268339] [rviz2_moveit.moveit.ros.motion_planning_frame]: Constructing new MoveGroup connection for group 'ar_manipulator' in namespace ''
```

**Comment by ycheng517** [comment]
I feel your moveit packages are out-of-date. Try updating your packages or ROS distro version, or run in docker instead. The follow commands should work for sure.

```
docker build -t ar4_ros_driver .
./run_in_docker.sh
colon build
source install/setup.bash
ros2 launch ar_moveit_config demo.launch.py
```

**Comment by ycheng517** [comment]
You can also try: https://github.com/ycheng517/ar4_ros_driver/issues/5

Not the same error but could be related.

**Comment by EbrahimAlmajed** [comment]
I tried the docker container it work when using perfectly 
`ros2 launch ar_moveit_config demo.launch.py`
but had some issues when trying to simulate in gazebo using
`ros2 launch ar_gazebo ar_gazebo.launch.py`
and I tried #5 with no results but you are right its most likely a moveit or ros2 installation issue I will reinstall it and see if that makes any difference.

**Comment by ycheng517** [comment]
gazebo demo should be working, feel free to send me the error you have

**Comment by EbrahimAlmajed** [comment]
After trying again with Rviz and Gazebo with the docker container it worked perfectly. I still have the local issue probably an insulation issue on my part. Thank you so much for your support.
